### ISSUE TITLE
Upgrade to Finagle 6.30.0

### ISSUE THREAD

**Issue by samn** [finagle/finagle-clojure#10]
Will require moving some things from http to httpx (potentially breaking).

**Comment by mosesn** [comment]
Wait, don't do it, we just moved back from httpx to http, so if you skip 6.29.0 you won't have to do it at all.

**Comment by mosesn** [comment]
The way it went down was: make two modules, http, httpx, migrate everyone to httpx, remove http, then we're going to rename httpx to http.  So the API will be a little different, but you don't have to change the module name.

**Comment by samn** [comment]
Awesome! Thanks for the heads up @mosesn :)

**Comment by samn** [comment]
upgraded to 6.33.0 in https://github.com/finagle/finagle-clojure/pull/14
