### ISSUE TITLE
Bridging the gap between Service objects and Clojure fns

### ISSUE THREAD

**Issue by bguthrie** [finagle/finagle-clojure#5]
It would be nice to support better interop between Finagle `Service`s––which are, after all, just functions of `Req -> Future[Rep]`––and Clojure fns. Certainly it would make testing and passing them around easier, and it would be nice not to have to call `apply` explicitly.

Unfortunately you can't just `extend-type` with `IFn`, for a number of reasons––it's not a protocol, for one thing, and you'd have to pick a concrete subclass of `Service`. But I could imagine two other workarounds.

First, you could write a wrapper that accepts a `Service` and uses `proxy` to return an object which extends `AFn`, which is an abstract implementation of `IFn` that's easier to override, and simultaneously implements `Service` by delegating to the given object. That'd give you back object which is both a `Service` and is Clojure-callable, but you'd lose any other typing information associated with the given `Service`.

Second, I could imagine changing the function signatures of `finagle-clojure` wrappers that currently accept services to allow them to accept Clojure functions as well, detecting them and wrapping them in a `scala.Function1` as necessary. It isn't as elegant and requires more wide-reaching changes, but might be safer.

Thoughts? Or maybe punt on it for now.

**Comment by samn** [comment]
i'm leaning towards the second solution right now, i think using a Clojure `IFn` as a `Service` is a more common operation than calling a `Service` like an `IFn`.

i have something sketched out, will fully implement after 0.2.0 is released.

**Comment by samn** [comment]
@bguthrie this is what i have sketched out so far. What do you think?

https://github.com/finagle/finagle-clojure/compare/sugar-fn

**Comment by bguthrie** [comment]
That's a nice polymorphic approach, looks good to me! If the general pattern could be extended more broadly, i.e. to `finagle-clojure.futures.map*` and friends, I'd probably prefer that form over the macroized `map` for threading convenience and general Clojure idiomaticity.

**Comment by samn** [comment]
yup! going to extend this to other functions that take `scala.Function1`s

**Comment by samn** [comment]
resolved in https://github.com/finagle/finagle-clojure/commit/4426c907a789df9e25b92bd6978300330cdad905
