### ISSUE TITLE
finagle-clojure/mysql: select-stmt doesn't wrap PreparedStatement parameters correctly

### ISSUE THREAD

**Issue by bguthrie** [finagle/finagle-clojure#8]
I suppose it speaks to the narrow audience for the mysql lib that the bug hasn't been spotted yet. :) Or that I didn't notice the other fix!

The `select-stmt` function should use the same `->Parameter` wrapper that `exec` does.

**Comment by samn** [comment]
Sorry that this broke
Thanks for fixing this in https://github.com/finagle/finagle-clojure/issues/9 @bguthrie 
i'll cut a release ASAP but may not be able to until early next week
